name: Unit Test

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v45

      - name: Filter out test files
        id: test_files
        run: |
          echo "TEST_FILES=$(echo \"${{ steps.changed_files.outputs.all_changed_files }}\" | grep 'src/test/kotlin/')" >> $GITHUB_ENV
          if [ -n "$TEST_FILES" ]; then
            echo "any_changed=true" >> $GITHUB_ENV
          else
            echo "any_changed=false" >> $GITHUB_ENV
          fi

      - name: Debug Changed Files
        run: |
          echo "All changed files: ${{ steps.test_files.outputs.TEST_FILES }}"
          echo "Any files changed: ${{ steps.test_files.outputs.any_changed }}"

      - name: setup JDK
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: actions/setup-java@v4

        with:
          distribution: 'corretto'
          java-version: '17'

      - name: setup Android SDK
        if: steps.test_files.outputs.any_changed == 'true'
        uses: android-actions/setup-android@v3

      - name: Run unit tests
        if: steps.test_files.outputs.any_changed == 'true'
        env:
          TEST_FILES: ${{ steps.test_files.outputs.TEST_FILES }}
        run: |
          chmod +x gradlew
          for file in ${TEST_FILES}; do
            echo "수행중인 테스트: $file"
            ./gradlew testDebugUnitTest --tests file
          done

      - name: Test Result
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/test-results/**/*.xml"