name: Unit Test

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        run: |
          git fetch origin dev
          changed_test_files=$(git diff --name-only origin/dev...HEAD \
            | grep 'src/test/kotlin/.*\.kt$' || true)
          if [ -z "$changed_test_files" ]; then
            echo "files=" >> $GITHUB_OUTPUT
          else
            test_classes=""
            for file in $changed_test_files
            do
              class_name=$(echo "$file" \
                | sed 's|^.*src/test/kotlin/||' \
                | sed 's|/|.|g' \
                | sed 's|.kt$||')
              test_classes="$test_classes $class_name"
            done
            echo "files=$test_classes" >> $GITHUB_OUTPUT
          fi

      - name: setup JDK
        if: ${{ steps.changed_files.outputs.files != '' }}
        uses: actions/setup-java@v4

        with:
          distribution: 'corretto'
          java-version: '17'

      - name: setup Android SDK
        if: ${{ steps.changed_files.outputs.files != '' }}
        uses: android-actions/setup-android@v3

      - name: gradlew permission
        if: ${{ steps.changed_files.outputs.files != '' }}
        run: chmod +x gradlew

      - name: Run unit tests
        if: ${{ steps.changed_files.outputs.files != '' }}
        run: |
          for class in ${{ steps.changed_files.outputs.files }}
          do
            echo "수행중인 테스트: $cls"
            ./gradlew testDebugUnitTest --tests "$cls"
          done

      - name: Test Result
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/test-results/**/*.xml"