name: Unit Test

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Commit Logs
        run: |
            echo "--- Last 100 commits in the repository ---"
            git log -100 --oneline
            echo "--- Comparing base and head commits ---"
            git log $(git merge-base origin/dev HEAD)..HEAD --oneline

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            src/test/kotlin/**

      - name: setup JDK
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: actions/setup-java@v4

        with:
          distribution: 'corretto'
          java-version: '17'

      - name: setup Android SDK
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: android-actions/setup-android@v3

      - name: Run unit tests
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          chmod +x gradlew
          for file in ${ALL_CHANGED_FILES}; do
            echo "수행중인 테스트: $file"
            ./gradlew testDebugUnitTest --tests file
          done

      - name: Test Result
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/test-results/**/*.xml"